version: 2

sources:
  - name: dev_wh  # A logical name for the source
    database: dev  # The database where the source resides
    schema: stage  # The schema where the source resides
    tables:
      - name: eaton_analysis  # The name of the table or view
